# Use postgres/example user/password credentials
version: '3.9'

# services:

#   db:
#     image: postgres
#     restart: always
#     # set shared memory limit when using docker-compose
#     shm_size: 128mb
#     # or set shared memory limit when deploy via swarm stack
#     #volumes:
#     #  - type: tmpfs
#     #    target: /dev/shm
#     #    tmpfs:
#     #      size: 134217728 # 128*2^20 bytes = 128Mb
#     environment:
#       POSTGRES_PASSWORD: example

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

services:
  postgres:
    image: postgres:14.6
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myapp # Default password, change it
      POSTGRES_DB: myapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: quangnghia.ns@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin # Default password, change it
    restart: unless-stopped

volumes:
  postgres-data:
